version: "3.9"

services:
  backend:
    container_name: weather-fastapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - OPENWEATHER_SEARCH_URL=${OPENWEATHER_SEARCH_URL}
      - OPENWEATHER_WEATHER_URL=${OPENWEATHER_WEATHER_URL}
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_SESSION_LIFETIME_SEC=${REDIS_SESSION_LIFETIME_SEC}
    ports:
      - "8080:8080"
    volumes:
      - ./weather_tracker:/weather_tracker:z
    depends_on:
      - database
      - cache

  database:
    container_name: weather-postgres
    image: "postgres:16-alpine"
    expose:
        - "5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:7.2
    container_name: weather-redis
    expose:
        - "6379"
    volumes:
      - redis_data:/data

  frontend:
    image: nginx:alpine
    container_name: weather-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:z
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:z
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data: